const KEY='debate-wheel-v1';
const seed={eventName:'Debate 2026',draws:[],sequence:0,roletas:{candidates:{name:'Candidatos',repeat:true,items:['Candidato 01','Candidato 02','Candidato 03','Candidato 04']},axes:{name:'Eixos temáticos',repeat:true,items:['Educação','Segurança','Saúde','Economia']},questions:{name:'Perguntas',repeat:false,groups:{Educação:['Qual deve ser a prioridade para a educação pública?','Como melhorar a aprendizagem?','Como valorizar os professores?','Que investimento deve vir primeiro?'],Segurança:['Como reduzir a violência?','Qual o papel da prevenção?','Como integrar as forças de segurança?','Como melhorar a iluminação urbana?','Como cuidar da juventude?'],Saúde:['Como ampliar o atendimento básico?','Como reduzir filas?','Como cuidar da saúde mental?','Como melhorar a prevenção?'],Economia:['Como gerar empregos?','Como apoiar pequenos negócios?','Como atrair investimentos?']}}}};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||seed;let pendingQuestion=null;
const wheelColors=['#ef8354','#70a7ff','#5dd39e','#c084fc','#f6c85f','#e86a92','#56c1b8','#9b8afb'];
let audioContext;
function wheelSound(kind='tick'){try{audioContext ||= new (window.AudioContext||window.webkitAudioContext)();const now=audioContext.currentTime;if(kind==='win'){const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='sine';o.frequency.setValueAtTime(440,now);o.frequency.exponentialRampToValueAtTime(880,now+.22);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.16,now+.02);g.gain.exponentialRampToValueAtTime(.0001,now+.42);o.connect(g);g.connect(audioContext.destination);o.start(now);o.stop(now+.45);return}const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='square';o.frequency.setValueAtTime(kind==='start'?180:95+Math.random()*25,now);o.frequency.exponentialRampToValueAtTime(kind==='start'?90:55,now+.045);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(kind==='start'?.08:.065,now+.004);g.gain.exponentialRampToValueAtTime(.0001,now+.055);o.connect(g);g.connect(audioContext.destination);o.start(now);o.stop(now+.06)}catch(e){}}
function paintWheel(id,labels,rotation=0){const c=document.getElementById(id);if(!c)return;const ctx=c.getContext('2d'),dpr=window.devicePixelRatio||1,size=320;c.width=size*dpr;c.height=size*dpr;ctx.scale(dpr,dpr);const cx=160,cy=160,r=153,n=labels.length;ctx.clearRect(0,0,size,size);ctx.save();ctx.translate(cx,cy);ctx.rotate(rotation);for(let i=0;i<n;i++){const a=-Math.PI/2+i*Math.PI*2/n,b=-Math.PI/2+(i+1)*Math.PI*2/n;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,r,a,b);ctx.closePath();ctx.fillStyle=wheelColors[i%wheelColors.length];ctx.fill();ctx.strokeStyle='#0b1020';ctx.lineWidth=3;ctx.stroke();ctx.save();ctx.rotate((a+b)/2);ctx.translate(r*.67,0);ctx.rotate(Math.PI/2);ctx.fillStyle='#0b1020';ctx.font='600 12px Manrope';ctx.textAlign='center';ctx.textBaseline='middle';let label=labels[i];if(label.length>16)label=label.slice(0,15)+'…';ctx.fillText(label,0,0);ctx.restore()}ctx.restore();ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.strokeStyle='#f5f1ea';ctx.lineWidth=4;ctx.stroke()}
function spinWheel(id,labels,onDone){wheelSound('start');const start=performance.now(),duration=3900,turns=8+Math.random()*3,target=Math.random()*Math.PI*2;let lastTick=0;function frame(now){const p=Math.min(1,(now-start)/duration),ease=1-Math.pow(1-p,4),rot=turns*Math.PI*2*ease+target;if(now-lastTick>Math.max(55,180-p*120)){wheelSound();lastTick=now}paintWheel(id,labels,rot);if(p<1)requestAnimationFrame(frame);else{wheelSound('win');onDone(labels[Math.floor(Math.random()*labels.length)])}}requestAnimationFrame(frame)}
function renderVerticalWheel(reelId,labels,selected){const reel=document.getElementById(reelId);if(!reel)return;const values=Array.from({length:20},()=>labels).flat();reel.innerHTML=values.map(x=>`<div class="reel-item">${x}</div>`).join('');const index=labels.length*10+Math.max(0,labels.indexOf(selected));reel.style.transform=`translateY(${-(index*70)+140}px)`}
function spinVertical(reelId,labels,onDone){if(!labels.length)return;wheelSound('start');const reel=document.getElementById(reelId),startIndex=labels.length*10+Math.floor(Math.random()*labels.length),targetIndex=startIndex+labels.length*4+Math.floor(Math.random()*labels.length),start=performance.now(),duration=4200;let last=-1;function frame(now){const p=Math.min(1,(now-start)/duration),ease=1-Math.pow(1-p,4),current=startIndex+(targetIndex-startIndex)*ease;reel.style.transform=`translateY(${-(current*70)+140}px)`;const tick=Math.floor(current);if(tick!==last){wheelSound();last=tick}if(p<1)requestAnimationFrame(frame);else{const item=labels[targetIndex%labels.length];wheelSound('win');onDone(item)}}requestAnimationFrame(frame)}
const $=s=>document.querySelector(s);const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));$('#saveState').textContent='● salvo agora'};
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
function showZoom(text){$('#zoomText').textContent=text;$('#zoomResult').classList.remove('hidden')}
$('#closeZoom').onclick=()=>$('#zoomResult').classList.add('hidden');
function itemsFor(key){return state.roletas[key].items.map((name,i)=>({name,used:false}));}
function usedQuestions(group){return state.draws.filter(d=>d.type==='question'&&d.group===group).map(d=>d.item)}
function availableQuestions(group){const used=usedQuestions(group);return (state.roletas.questions.groups[group]||[]).filter(q=>!used.includes(q))}
function drawFrom(list){return list[Math.floor(Math.random()*list.length)]}
function addDraw(type,roleta,item,group=''){state.sequence++;state.draws.push({id:state.sequence,time:new Date().toISOString(),type,roleta,item,group});save();render()}
function render(){ $('#eventName').textContent=state.eventName;$('#drawCount').textContent=state.draws.length;let total=Object.values(state.roletas.questions.groups).flat().length;let used=new Set(state.draws.filter(d=>d.type==='question').map(d=>d.item));$('#availableCount').textContent=total-used.size;const last=state.draws.at(-1);$('#lastDraw').textContent=last?`${last.roleta} — ${last.item}`:'Nenhum sorteio ainda';renderPicker();renderAdmin();renderVerticalWheel('candidateReel',state.roletas.candidates.items);renderVerticalWheel('axisReel',state.roletas.axes.items);}
function renderPicker(){const p=$('#axisPicker'),old=p.value||Object.keys(state.roletas.questions.groups)[0];p.innerHTML=Object.keys(state.roletas.questions.groups).map(x=>`<option>${x}</option>`).join('');if([...p.options].some(o=>o.value===old))p.value=old;updateAvailability();renderVerticalWheel('questionReel',availableQuestions(p.value))}
function updateAvailability(){const g=$('#axisPicker').value;const n=availableQuestions(g).length;const total=state.roletas.questions.groups[g].length;$('#questionAvailability').textContent=n?`${n} de ${total} disponíveis`:'TODOS OS ITENS DESTE EIXO JÁ FORAM UTILIZADOS';}
function result(id,text){const el=$(id);el.innerHTML=`<strong>${text}</strong>`;el.classList.remove('reveal');void el.offsetWidth;el.classList.add('reveal')}
function renderAdmin(){const allQ=Object.values(state.roletas.questions.groups).flat();const usedQ=new Set(state.draws.filter(d=>d.type==='question').map(d=>d.item));$('#overviewGrid').innerHTML=[['Sorteios realizados',state.draws.length,'nesta sessão'],['Perguntas utilizadas',usedQ.size,'de '+allQ.length],['Perguntas disponíveis',allQ.length-usedQ.size,'prontas para uso']].map(x=>`<div class="overview-card"><span class="eyebrow">${x[0].toUpperCase()}</span><span class="big">${x[1]}</span><p>${x[2]}</p></div>`).join('');let html='';[['candidates',state.roletas.candidates.items],['axes',state.roletas.axes.items]].forEach(([key,arr])=>{html+=`<div class="editor-group"><div class="editor-head"><h3>${state.roletas[key].name}</h3><span class="repeat-badge">↻ permite repetição</span></div><div class="editor-list">${arr.map((x,i)=>`<div class="item-row"><span class="status-dot"></span><span class="item-name">${x}</span><span class="status-label">disponível</span></div>`).join('')}</div></div>`});Object.entries(state.roletas.questions.groups).forEach(([g,arr])=>{html+=`<div class="editor-group"><div class="editor-head"><h3>${g}</h3><button class="mini-btn reset-group" data-group="${g}">Reiniciar eixo</button></div><div class="editor-list">${arr.map((x,i)=>{let u=usedQ.has(x);return `<div class="item-row"><span class="status-dot ${u?'used':''}"></span><span class="item-name">${x}</span><span class="status-label">${u?'utilizada':'disponível'}</span>${u?`<button class="mini-btn restore" data-item="${encodeURIComponent(x)}">Restaurar</button>`:''}</div>`}).join('')}</div></div>`});$('#itemsEditor').innerHTML=html;const rows=state.draws.slice().reverse().map(d=>`<div class="history-row"><span>${new Date(d.time).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</span><span>${d.roleta}</span><span>${d.item}</span><span>${d.type==='question'?'confirmado':'realizado'}</span></div>`).join('');$('#historyTable').innerHTML=`<div class="table-wrap"><div class="history-row head"><span>Horário</span><span>Roleta</span><span>Item sorteado</span><span>Status</span></div>${rows||'<div class="empty">Nenhum sorteio registrado.</div>'}</div>`;document.querySelectorAll('.reset-group').forEach(b=>b.onclick=()=>resetGroup(b.dataset.group));document.querySelectorAll('.restore').forEach(b=>b.onclick=()=>restoreQuestion(decodeURIComponent(b.dataset.item)))}
function confirmAction(title,text,fn){$('#modalTitle').textContent=title;$('#modalText').textContent=text;$('#confirmModal').classList.remove('hidden');$('#modalConfirm').onclick=()=>{$('#confirmModal').classList.add('hidden');fn()};$('#modalCancel').onclick=()=>$('#confirmModal').classList.add('hidden')}
$('#drawCandidate').onclick=()=>{const b=$('#drawCandidate');b.disabled=true;spinVertical('candidateReel',state.roletas.candidates.items,x=>{result('#candidateResult',x);addDraw('candidate','Candidatos',x);showZoom(x);toast('Candidato sorteado');b.disabled=false})};$('#drawAxis').onclick=()=>{const b=$('#drawAxis');b.disabled=true;spinVertical('axisReel',state.roletas.axes.items,x=>{result('#axisResult',x);$('#axisPicker').value=x;updateAvailability();addDraw('axis','Eixos temáticos',x);showZoom(x);toast('Eixo sorteado');b.disabled=false})};$('#axisPicker').onchange=updateAvailability;
function prepareQuestion(){const g=$('#axisPicker').value, list=availableQuestions(g);if(!list.length){toast('Não há perguntas disponíveis neste eixo');return}const b=$('#drawQuestion');b.disabled=true;spinVertical('questionReel',list,x=>{pendingQuestion={g,item:x};result('#questionResult',x);b.disabled=false;b.innerHTML='Confirmar pergunta';b.onclick=confirmQuestion;$('#questionResult').insertAdjacentHTML('beforeend','<button class="mini-btn" id="redoQuestion">Refazer sorteio</button>');$('#redoQuestion').onclick=prepareQuestion})}
function confirmQuestion(){if(!pendingQuestion)return;addDraw('question',`Perguntas / ${pendingQuestion.g}`,pendingQuestion.item,pendingQuestion.g);showZoom(pendingQuestion.item);toast('Pergunta confirmada e marcada como utilizada');pendingQuestion=null;$('#drawQuestion').innerHTML='Sortear pergunta <span>→</span>';$('#drawQuestion').onclick=prepareQuestion;$('#questionResult').innerHTML='<span class="result-placeholder">Pronto para sortear</span>'}
$('#drawQuestion').onclick=prepareQuestion;
$('#resetQuestions').onclick=()=>resetGroup($('#axisPicker').value);function resetGroup(g){confirmAction('Reiniciar eixo?',`Todas as perguntas de ${g} voltarão a ficar disponíveis.`,()=>{state.draws=state.draws.filter(d=>!(d.type==='question'&&d.group===g));save();render();toast('Eixo reiniciado')})}function restoreQuestion(item){const d=state.draws.find(x=>x.type==='question'&&x.item===item);if(d){state.draws=state.draws.filter(x=>x!==d);save();render();toast('Pergunta restaurada')}}
$('#resetEvent').onclick=()=>confirmAction('Reiniciar todas as perguntas?', 'O histórico de perguntas será apagado e todas voltarão a ficar disponíveis.',()=>{state.draws=[];state.sequence=0;save();render();toast('Evento reiniciado')});$('#renameEvent').onclick=()=>{const n=prompt('Nome do evento:',state.eventName);if(n){state.eventName=n;save();render()}};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active-view'));$('#'+(b.dataset.view==='present'?'presentView':'adminView')).classList.add('active-view')});document.querySelectorAll('.side-link').forEach(b=>b.onclick=()=>{document.querySelectorAll('.side-link').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.admin-panel').forEach(x=>x.classList.add('hidden'));$('#admin'+b.dataset.admin[0].toUpperCase()+b.dataset.admin.slice(1)).classList.remove('hidden')});render();
